# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200/
    editable: true
    isDefault: false
