# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  httpcheck/frontendproxy:
    targets:
      - endpoint: http://frontendproxy:${env:ENVOY_PORT}
  redis:
    endpoint: "redis-cart:6379"
    collection_interval: 10s

exporters:
  debug:
  otlp/tempo: # traces
    endpoint: "tempo:4317"
    tls:
      insecure: true
  otlp/jaeger: # traces
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlphttp/prometheus: # metrics
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true
  opensearch: # logging
    logs_index: otel
    http:
      endpoint: "http://opensearch:9200"
      tls:
        insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true
  datadog:
    api:
      site: <DD_SITE>
      key: ${env:DD_API_KEY}

processors:
  batch:

connectors:
  spanmetrics:

# Pipeline enables all the already defined components
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, otlp/tempo, debug, spanmetrics]
    metrics:
      receivers: [httpcheck/frontendproxy, redis, otlp, spanmetrics]
      processors: [batch]
      exporters: [debug, datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch, loki, debug]
